# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
    inputs:
      branche:
        description: 'Branche'
        required: true
      commit:
        description: 'Commit'
        required: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: JordanKikleo/child_repo
          ssh-key: ${{ secrets.CHILD_COMMIT_KEY }}
          fetch-depth: 0
          path: child_repo

      - name: Handle trigger
        run: |
          echo "Branch: ${{ github.event.inputs.branche }}"
          echo "Commit: ${{ github.event.inputs.commit }}"

      - name: Move child_repo directory
        run: mv child_repo ../

      - name: List files
        run: |
          ls ..

      - name: Get latest tag
        run: |
          cd ../child_repo
          echo "TAG=$(git tag --sort=-version:refname | head -n 1 || echo 'v1.0.0')" >> $GITHUB_ENV

      - name: Display latest tag
        run: echo "Latest tag is ${{ env.TAG }}"