# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: JordanKikleo/child_repo
          ssh-key: ${{ secrets.CHILD_COMMIT_KEY }}
          path: ./child_repo


      - name: List files
        run: |
          ls

      - name: Get latest tag
        run: |
          cd child_repo
          echo "TAG=$(git tag --sort=-version:refname | head -n 1 || echo 'v1.0.0')" >> $GITHUB_ENV

      - name: Display latest tag
        run: echo "Latest tag is ${{ env.TAG }}"