# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Checkout private tools
        uses: actions/checkout@master
        with:
          repository: JordanKikleo/child_repo
          ssh-key: ${{ secrets.AUTH_TOKEN }}

      - name: List files
        run: |
          ls